# Generated by Django 2.2.15 on 2024-01-27 11:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='memematch',
            name='participants',
            field=models.ManyToManyField(to='api.UserModel'),
        ),
        migrations.AlterField(
            model_name='memematch',
            name='hoster',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hoster_user', to='api.UserModel'),
        ),
    ]
