# Generated by Django 2.2.15 on 2024-01-27 03:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MemeMatch',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reference', models.CharField(max_length=255)),
                ('datetime_open', models.DateTimeField()),
                ('datetime_close', models.DateTimeField(null=True)),
                ('is_open', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='MemePlay',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('meme', models.BinaryField()),
                ('score', models.FloatField(default=0)),
                ('meme_match', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.MemeMatch')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.UserModel')),
            ],
        ),
        migrations.CreateModel(
            name='Vote',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.IntegerField(default=0)),
                ('meme_play', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.MemePlay')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.UserModel')),
            ],
        ),
    ]
