version: '3'

services:

  memerank:
    build: .    
    image: memerank:devel
    restart: on-failure
    container_name: memerank_container
    command: python3 manage.py runserver 0.0.0.0:5024
    env_file: ggj24/environment/env
    volumes:
      - .:/app
      - static_data:/app/static
    ports:
      - "5024:5024"

volumes:
  static_data: